### ISSUE TITLE
🏆 Awesome and epic initiative from lwuert

### ISSUE THREAD

**Issue by lwuert** [lwuert/training#8]
- [ ] #9
- [ ] #10
- [ ] #11

**Comment by lwuert** [comment]
- [ ] 🎸 A feature from [username] that rocks
- [ ] ⚡ Another epic feature from [username]
- [ ] 🔥 Hot feature from [username]
